' Launches a command with NO visible window - generated by
' setup_task_scheduler.ps1, used as the Task Scheduler action instead of
' calling python.exe directly (which always briefly flashes a console
' window, even when run from Task Scheduler). Do not run this by hand.
Set objShell = CreateObject("WScript.Shell")
objShell.CurrentDirectory = WScript.Arguments(0)
pythonPath = WScript.Arguments(1)
pythonArgs = WScript.Arguments(2)
commandLine = Chr(34) & pythonPath & Chr(34) & " " & pythonArgs
objShell.Run commandLine, 0, True
