<#
Sets up TWO Windows Task Scheduler tasks so the Financial Sentiment
Dashboard's ingestion layer keeps refreshing without you having to run it
by hand:

  - A "fast" task every 5 minutes: prices, StockTwits, Reddit, Finnhub.
  - A "slow" task every 15 minutes: FinViz + Google News.

Split 2026-07-12: FinViz only updates news ~every 30 min and its terms
discourage high-frequency automated hits; Google News RSS is unofficial
with no documented rate limit either. Polling either one every 5 min would
just refetch the same headlines 3x as often for no new data, while raising
scraping-detection risk for no benefit. The other sources all comfortably
support 5 minutes. See main.py --fast-only / --slow-only.

Runs hidden, added 2026-07-12 (Calvin noticed a command prompt window
flashing open and closing every few minutes): Task Scheduler always briefly
allocates a visible console window for a task whose action is python.exe
directly, even with no other setting to suppress it - a well-known Windows
quirk, not something fixable via a Task Scheduler checkbox alone. The
standard workaround is to have the task launch a tiny VBScript
(`run_hidden.vbs`, generated by this script) via wscript.exe instead -
wscript.exe has no console of its own, and its .Run method with a window
style of 0 launches python.exe fully hidden, so nothing flashes on screen.

USAGE (run once, from inside this project folder):
    powershell -ExecutionPolicy Bypass -File .\setup_task_scheduler.ps1

If you get an "Access Denied" error, right-click PowerShell and choose
"Run as Administrator", then run the command again.

Safe to re-run - it replaces any existing tasks with the same names, so you
can use it again later if you want to change the intervals (edit
$FastRepetitionMinutes / $SlowRepetitionMinutes below), move the project
folder, or (like now) pick up the hidden-window fix.
#>

$FastTaskName = "FinancialSentimentDashboard-Ingestion-Fast"
$SlowTaskName = "FinancialSentimentDashboard-Ingestion-Slow"
$FastRepetitionMinutes = 5
$SlowRepetitionMinutes = 15
$ProjectDir = $PSScriptRoot
$VenvPythonPath = Join-Path $ProjectDir ".venv\Scripts\python.exe"
$PythonPath = if (Test-Path -LiteralPath $VenvPythonPath) {
    $VenvPythonPath
} else {
    (Get-Command python -ErrorAction SilentlyContinue).Source
}

if (-not $PythonPath) {
    Write-Host "Could not find python.exe on PATH." -ForegroundColor Red
    Write-Host "If you're using a virtual environment, activate it first and re-run this script." -ForegroundColor Red
    Write-Host "Otherwise, edit this script and hardcode `$PythonPath to the full path to python.exe." -ForegroundColor Red
    exit 1
}

Write-Host "Project folder: $ProjectDir"
Write-Host "Python path:     $PythonPath"
Write-Host "Fast interval:   every $FastRepetitionMinutes minutes (prices, StockTwits, Reddit, Finnhub)"
Write-Host "Slow interval:   every $SlowRepetitionMinutes minutes (FinViz, Google News)"

# Generated hidden-launcher, added 2026-07-12 - see the module docstring
# above for why this exists. Args: 0 = working directory, 1 = Python path,
# 2 = Python argument string. The VBScript constructs the quoted command
# itself so interpreter paths containing spaces remain valid. Re-written
# every time this script runs so it always matches the current project.
$VbsPath = Join-Path $ProjectDir "run_hidden.vbs"
$VbsContent = @'
' Launches a command with NO visible window - generated by
' setup_task_scheduler.ps1, used as the Task Scheduler action instead of
' calling python.exe directly (which always briefly flashes a console
' window, even when run from Task Scheduler). Do not run this by hand.
Set objShell = CreateObject("WScript.Shell")
objShell.CurrentDirectory = WScript.Arguments(0)
pythonPath = WScript.Arguments(1)
pythonArgs = WScript.Arguments(2)
commandLine = Chr(34) & pythonPath & Chr(34) & " " & pythonArgs
objShell.Run commandLine, 0, True
'@
Set-Content -Path $VbsPath -Value $VbsContent -Encoding ASCII
Write-Host "Hidden launcher: $VbsPath"

$Settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable

function Register-IngestionTask {
    param(
        [string]$TaskName,
        [string]$PythonArgument,
        [int]$RepetitionMinutes,
        [string]$Description
    )

    # The task's action is wscript.exe running run_hidden.vbs, which in turn
    # launches "python.exe main.py --fast-only" (etc.) with window style 0 -
    # this is what actually suppresses the console flash; see the module
    # docstring above.
    $TaskArgument = "`"$VbsPath`" `"$ProjectDir`" `"$PythonPath`" `"$PythonArgument`""
    $Action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument $TaskArgument -WorkingDirectory $ProjectDir

    # Fire once shortly after creation, then repeat on the configured
    # interval for (effectively) forever - Task Scheduler's cmdlets don't
    # have a true "indefinite" duration, so 10 years is the standard
    # workaround.
    $Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
        -RepetitionInterval (New-TimeSpan -Minutes $RepetitionMinutes) `
        -RepetitionDuration (New-TimeSpan -Days 3650)

    # If this task happens to be mid-run right now (e.g. re-running this
    # script exactly on the 5-minute mark), Windows won't let its definition
    # be replaced until the running instance ends - stopping it first avoids
    # the "Cannot create a file when that file already exists" error this
    # caused for Calvin. -Force on Register-ScheduledTask (below) then
    # overwrites the existing task in one step, instead of a separate
    # Unregister + Register that can race with Task Scheduler internals.
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1

    try {
        Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings `
            -Description $Description -Force -ErrorAction Stop | Out-Null
        Write-Host "  Registered '$TaskName'" -ForegroundColor Green
        return $true
    } catch {
        Write-Host "  FAILED to register '$TaskName': $($_.Exception.Message)" -ForegroundColor Red
        Write-Host "  Try closing Task Scheduler if it's open, or wait a moment and re-run this script." -ForegroundColor Red
        return $false
    }
}

$FastOk = Register-IngestionTask -TaskName $FastTaskName -PythonArgument "main.py --fast-only" `
    -RepetitionMinutes $FastRepetitionMinutes `
    -Description "Runs prices, StockTwits, Reddit, and Finnhub ingestion every $FastRepetitionMinutes minutes."

$SlowOk = Register-IngestionTask -TaskName $SlowTaskName -PythonArgument "main.py --slow-only" `
    -RepetitionMinutes $SlowRepetitionMinutes `
    -Description "Runs FinViz and Google News ingestion every $SlowRepetitionMinutes minutes."

Write-Host ""
if ($FastOk -and $SlowOk) {
    Write-Host "Tasks created:" -ForegroundColor Green
    Write-Host "  '$FastTaskName' - starts within 1 minute, repeats every $FastRepetitionMinutes minutes" -ForegroundColor Green
    Write-Host "  '$SlowTaskName' - starts within 1 minute, repeats every $SlowRepetitionMinutes minutes" -ForegroundColor Green
} else {
    Write-Host "One or more tasks failed to register - see FAILED messages above. Re-run this script to retry." -ForegroundColor Red
    exit 1
}
Write-Host ""
Write-Host "Useful commands:"
Write-Host "  Check status:  Get-ScheduledTask -TaskName '$FastTaskName' | Get-ScheduledTaskInfo"
Write-Host "  Run right now: Start-ScheduledTask -TaskName '$FastTaskName'"
Write-Host "  Remove both:   Unregister-ScheduledTask -TaskName '$FastTaskName'; Unregister-ScheduledTask -TaskName '$SlowTaskName'"
Write-Host "  View logs:     Get-Content .\logs\ingestion.log -Tail 30 -Wait"
Write-Host ""
Write-Host "If you previously ran the old single-task version of this script, remove it manually:" -ForegroundColor Yellow
Write-Host "  Unregister-ScheduledTask -TaskName 'FinancialSentimentDashboard-Ingestion' -ErrorAction SilentlyContinue" -ForegroundColor Yellow
